### PR TITLE
Use compile False in bundle

### PR DESCRIPTION
**Pull request by wesleybl**
We don't have resource less or requirejs.

### CODE REVIEW

**Comment by wesleybl** [comment]
@tisto can you remove Travis from the repository please? It is still being required in PR.

**Comment by wesleybl** [comment]
@mauritsvanrees can you please review this PR and remove Travis from this repository?

**Comment by mauritsvanrees** [comment]
I have removed the required Travis check.

The changes look okay, but I don't really know this package.

**Comment by wesleybl** [comment]
@tisto @wkbkhard @laulaz can you please take a look here?

@tisto can you please create a new release after the merge?

**Comment by wesleybl** [comment]
@tisto can you please generate a new release?

**Pull request merged**
