### PR TITLE
Python3branch - Travis Fix

### PR DESCRIPTION
**Pull request by tisto**

### CODE REVIEW

**Comment by laulaz** [comment]
Buildout has been fixed / upgraded to 5.2.2.
Travis builds are now succeeding 👍 

@tisto can we merge this into master ?

_We plan to work on making this package compatible with Plone 6 (only a few changes) & add Github actions._

**Comment by tisto** [comment]
@laulaz sure. go ahead!

**Comment by wesleybl** [comment]
@tisto @laulaz can you do a release please?

**Comment by laulaz** [comment]
@wesleybl sorry I don't have the rights on Pypi

**Comment by wesleybl** [comment]
Can someone please create a release?

@tisto @vincentfretin @tdesvenain @sgeulette @gbastien

**Comment by tisto** [comment]
@wesleybl 2.0.0 released.

**Comment by wesleybl** [comment]
@tisto Thanks!

**Pull request merged**
